// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrSHRNIVgMcqaFLT6IT5VKe1BDS9MSH7c',
    appId: '1:1001077080153:web:bd14d5e6ee78c264217148',
    messagingSenderId: '1001077080153',
    projectId: 'lockers-app-d6caa',
    authDomain: 'lockers-app-d6caa.firebaseapp.com',
    databaseURL: 'https://lockers-app-d6caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-d6caa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMcZmF0_uuy8RQ5gItElxRcN2aQ6sWSA',
    appId: '1:1001077080153:android:2d2471f0d61bd7b9217148',
    messagingSenderId: '1001077080153',
    projectId: 'lockers-app-d6caa',
    databaseURL: 'https://lockers-app-d6caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-d6caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZtaWeY96KHbN3yGgaK2G_pFTepLeLg-g',
    appId: '1:1001077080153:ios:78aabb47718f7334217148',
    messagingSenderId: '1001077080153',
    projectId: 'lockers-app-d6caa',
    databaseURL: 'https://lockers-app-d6caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-d6caa.appspot.com',
    iosClientId: '1001077080153-5ektkeq125ufkdqtepe2qpuvk2gue9bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZtaWeY96KHbN3yGgaK2G_pFTepLeLg-g',
    appId: '1:1001077080153:ios:75ad0880b759b485217148',
    messagingSenderId: '1001077080153',
    projectId: 'lockers-app-d6caa',
    databaseURL: 'https://lockers-app-d6caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-d6caa.appspot.com',
    iosClientId: '1001077080153-7rig9rrpq20usi9fknj88piemb39u58m.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockersApp.RunnerTests',
  );
}
