// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEm-Uue1yUdhOIqvcNHIeebF2ZUCP0kg',
    appId: '1:878604521951:web:37fc37eaae8242ce84b46a',
    messagingSenderId: '878604521951',
    projectId: 'lockerapp-3b54f',
    authDomain: 'lockerapp-3b54f.firebaseapp.com',
    databaseURL:
        'https://lockerapp-3b54f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerapp-3b54f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrIHShPCdlS-i-mcshbE129QhjZo84daI',
    appId: '1:878604521951:android:a34e850e6e5e399284b46a',
    messagingSenderId: '878604521951',
    projectId: 'lockerapp-3b54f',
    databaseURL:
        'https://lockerapp-3b54f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerapp-3b54f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCQWGm1LFwWxTHieiacIyG9x_cbJyawpk',
    appId: '1:878604521951:ios:88cffa21acfdac2784b46a',
    messagingSenderId: '878604521951',
    projectId: 'lockerapp-3b54f',
    databaseURL:
        'https://lockerapp-3b54f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerapp-3b54f.appspot.com',
    iosClientId:
        '878604521951-4cgqrvrgo9veirkjis77u1dqkkufgg3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCQWGm1LFwWxTHieiacIyG9x_cbJyawpk',
    appId: '1:878604521951:ios:43207f9971c4019884b46a',
    messagingSenderId: '878604521951',
    projectId: 'lockerapp-3b54f',
    databaseURL:
        'https://lockerapp-3b54f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockerapp-3b54f.appspot.com',
    iosClientId:
        '878604521951-uv6gv8tpegqvdv5pcho0d8eiogie0pfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.lockersApp.RunnerTests',
  );
}
